apiVersion: v1
kind: Service
metadata:
  name: my-chatbot-service
  namespace: awsbedrockworkshop # 👈 Namespace added here
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: chatbot